### ISSUE TITLE
Music Blitz? MOAR LIKE BALLROOM BLITZ AMIRIT?!?

### ISSUE THREAD

**Issue by robertdfrench** [saites/music-blitz#1]
![Ballroom Blitz](https://images-na.ssl-images-amazon.com/images/I/41fGR4L6QDL._SX300_.jpg)

**Comment by saites** [comment]
Basically, yes :)

I'm putting together online documentation for [the app I published](https://play.google.com/store/apps/details?id=com.saites.spotlight&hl=en), and github pages seems like a pretty sensible place for it, especially since the code is in a private git repo.
