### ISSUE TITLE
Z strips no longer being discovered

### ISSUE THREAD

**Issue by ghost** [saites/music-blitz#31]
As of the most recent firmware update to the controllers (2.76RC2) they are no longer detected by the app during the discover phase. Not exactly sure why, I haven't compared the packets passing between the controller and whatever is communicating with it between the firmware it starts with and the most recent so I've no idea what changed exactly but I've noticed that several legacy implementations of the LAN protocol are no longer returning the strips during discovery so I'm thinking the message changed.

**Comment by saites** [comment]
Crap :( Thank you for letting me know.

I have been super lagging any development on this recently due to a crazy ramp in my day job. Thankfully, that's finally starting to slow down a bit.

**Comment by ghost** [comment]
Well, allow me to lighten the load! I failed basic troubleshooting at some point I guess because after removing and reinstalling the app, it detects them again. But that's an entirely different issue so I'd say this seems to be solved at this point. 👍
